name: criss_cross_IIB
lam_type: constant
lam_params:
  val:
  - 0.4
  - 0.0
  - 0.2
network:
- - 1
  - 0
  - 1
- - 0
  - 1
  - 0
mu:
- - 2.0
  - 0.0
  - 0.5
- - 0.0
  - 1.0
  - 0.0
h:
- 1
- 1
- 1
init_queues:
- 0
- 0
- 0
queue_event_options:
- - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 1.0
  - 0.0
- - 0.0
  - 0.0
  - 1.0
- - -1.0
  - 1.0
  - 0.0
- - 0.0
  - -1.0
  - 0.0
- - 0.0
  - 0.0
  - -1.0
train_T: 20000
test_T: 200000
num_pool: 1
q: 3
s: 2
