name: criss_cross_IIB_small
lam_type: constant
lam_params:
  val:
  - 0.3
  - 0.3
  - 0.0
network:
- - 1
  - 0
  - 1
- - 0
  - 1
  - 0
mu:
- - 1.0
  - 0.0
  - 1.0
- - 0.0
  - 0.8
  - 0.0
h:
- 1.0
- 2.0
- 1
init_queues:
- 0
- 0
- 0
queue_event_options:
- - 1.0
  - 0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0
  - 1.0
- - -1.0
  - 1.0
  - 0.0
- - 0.0
  - -1.0
  - 0.0
- - 0.0
  - 0.0
  - -1.0
train_T: 100
test_T: 100
num_pool: 1
q: 3
s: 2

